#ifndef SPI_CFG_H_
#define SPI_CFG_H_


/*  LSB_FIRST      MSB_FIRST */
#define DATA_ORDER   LSB_FIRST
/*  MASTER      SLAVE       */
#define SPI_STATE    SLAVE
/* LEADING_RISING  LEADING_FAILING */
#define SPI_CLK_POLARITY  LEADING_FAILING
/* FIRST_CLK   SEC_CLK */
#define SPI_CLK_PHASE  FIRST_CLK
#if SPI_STATE==MASTER
/* FREQ_DIV_2   FREQ_DIV_4  FREQ_DIV_8  FREQ_DIV_16  FREQ_DIV_32  FREQ_DIV_64  FREQ_DIV_128*/
#define SCK_FREQUENCY  FREQ_DIV_8
#endif
#endif
